# Generated by Django 4.2 on 2025-10-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='correo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin_manual',
            field=models.BooleanField(default=False, verbose_name='Administrador manual'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
