# Generated by Django 4.2 on 2025-10-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_customuser_correo_customuser_is_admin_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
