# Generated by Django 4.2 on 2025-11-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='apellidos',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='documento_identidad',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='es_estatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='es_estudiante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='igms_productos',
            field=models.FileField(blank=True, null=True, upload_to='igms/'),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='institucion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='metodo_pago',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='nombre_emprendedor',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='numero_documento',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='tiene_domicilio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='tipo_documento',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='tipo_emprendimiento',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='vende_en_institucion',
            field=models.BooleanField(default=False),
        ),
    ]
