# Generated by Django 4.2 on 2025-11-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_emprendimiento_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
