# Generated by Django 4.2 on 2026-01-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_emprendimiento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='perfiles/default_user.png', null=True, upload_to='perfiles/'),
        ),
    ]
