# Generated by Django 4.2 on 2026-01-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_customuser_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendimiento',
            name='estado',
            field=models.CharField(choices=[('revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='revision', max_length=20),
        ),
    ]
