# Generated by Django 4.2 on 2026-01-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_emprendimiento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_admin_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='metodo_pago',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='tipo_documento',
            field=models.CharField(max_length=20),
        ),
    ]
