# Generated by Django 4.2 on 2026-03-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_emprendimiento_fecha_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='es_emprendedor',
            field=models.BooleanField(default=False),
        ),
    ]
