# Generated by Django 4.2 on 2026-04-13 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('categoria', models.CharField(choices=[('comida', 'Comida'), ('ropa', 'Ropa'), ('tecnologia', 'Tecnología'), ('hogar', 'Hogar'), ('otros', 'Otros')], max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='usuarios.emprendimiento')),
            ],
        ),
        migrations.CreateModel(
            name='EmprendimientoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='emprendimientos/galeria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='usuarios.emprendimiento')),
            ],
        ),
    ]
