# Generated by Django 4.2 on 2026-04-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_producto_emprendimientoimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vio_tutorial_emprendimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='personalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
