# Generated by Django 4.2 on 2026-05-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_producto_disponible_producto_stock_producto_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='google_maps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='mostrar_ubicacion',
            field=models.BooleanField(default=False),
        ),
    ]
