# Generated by Django 4.2 on 2026-05-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_emprendimiento_google_maps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('01', 'Comida'), ('02', 'Ropa'), ('03', 'Accesorios'), ('04', 'Tecnología'), ('05', 'Belleza'), ('06', 'Hogar'), ('07', 'Artesanías'), ('08', 'Papelería'), ('09', 'Mascotas'), ('10', 'Otros')], default='10', max_length=2),
        ),
    ]
