# Generated by Django 4.2 on 2026-05-10 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_categoriaproducto_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprendimiento',
            name='tipo_emprendimiento',
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprendimientos', to='usuarios.categoriaproducto'),
        ),
    ]
