# Generated by Django 4.2 on 2026-05-11 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_producto_categoria'),
        ('usuarios', '0016_remove_emprendimiento_tipo_emprendimiento_and_more'),
    ]

    operations = [
    ]
