# Generated by Django 4.2 on 2026-05-11 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_merge_20260510_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_indefinido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='usuarios.categoriaproducto'),
        ),
    ]
