# Generated by Django 4.2 on 2026-05-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_producto_stock_indefinido_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('info', 'Información'), ('panel_atencion', 'Panel de Atención')], max_length=20),
        ),
    ]
