# Generated by Django 4.2 on 2026-05-14 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_producto_stock_indefinido_alter_producto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido', 'Hacer pedido'), ('disponibilidad', 'Consultar disponibilidad'), ('personalizacion', 'Consultar personalización'), ('pago', 'Métodos de pago'), ('chat', 'Hablar con el vendedor')], max_length=30)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('respondida', 'Respondida'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_contacto', to='usuarios.emprendimiento')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_contacto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
