# Generated by Django 4.2 on 2026-05-18 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_producto_stock_indefinido_alter_producto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_solicitudcontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='usuarios.emprendimiento')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizado'],
                'unique_together': {('usuario', 'emprendimiento', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sistema', 'Sistema'), ('usuario', 'Usuario'), ('emprendedor', 'Emprendedor')], default='sistema', max_length=20)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='social.chat')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
