# Generated by Django 4.2 on 2026-05-18 02:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_producto_stock_indefinido_alter_producto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0003_chat_mensajechat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('usuario', 'emprendimiento')},
        ),
    ]
