# Generated by Django 4.2 on 2026-05-18 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_producto_stock_indefinido_alter_producto_categoria'),
        ('social', '0004_alter_chat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcontacto',
            name='tipo',
            field=models.CharField(choices=[('pedido', 'Hacer pedido'), ('disponibilidad', 'Consultar disponibilidad'), ('personalizacion', 'Consultar personalización'), ('pago', 'Métodos de pago'), ('chat', 'Hablar con el vendedor'), ('otro', 'Otro')], max_length=30),
        ),
        migrations.CreateModel(
            name='RespuestaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_rapidas', to='usuarios.emprendimiento')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
